- name: Configure Slurm cluster
  hosts: controller_node_group, worker_node_group, login_node_group
  roles:
    # - role: storage
    - role: passwordless
    # - role: ntp
    - role: munge
    - role: slurm

- name: Install docker on the login node
  hosts: login_node_group
  roles:
    - role: docker

- name: Install NVIDIA toolkit
  hosts: worker_node_group
  roles:
    - role: nvidia
